/// Flutter icons Nectar
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Nectar
///      fonts:
///       - asset: fonts/Nectar.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Nectar {
  Nectar._();

  static const _kFontFam = 'Nectar';
  static const String? _kFontPkg = null;

  static const IconData favourite = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData store = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData explore = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cart = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
